# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/brobey/Programs/GlobalSums

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/brobey/Programs/GlobalSums

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brobey/Programs/GlobalSums/CMakeFiles /Users/brobey/Programs/GlobalSums/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brobey/Programs/GlobalSums/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named globalsums

# Build rule for target.
globalsums: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 globalsums
.PHONY : globalsums

# fast build rule for target.
globalsums/fast:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/build
.PHONY : globalsums/fast

do_full_qdsum.o: do_full_qdsum.c.o

.PHONY : do_full_qdsum.o

# target to build an object file
do_full_qdsum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum.c.o
.PHONY : do_full_qdsum.c.o

do_full_qdsum.i: do_full_qdsum.c.i

.PHONY : do_full_qdsum.i

# target to preprocess a source file
do_full_qdsum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum.c.i
.PHONY : do_full_qdsum.c.i

do_full_qdsum.s: do_full_qdsum.c.s

.PHONY : do_full_qdsum.s

# target to generate assembly for a file
do_full_qdsum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum.c.s
.PHONY : do_full_qdsum.c.s

do_full_qdsum_wtrunc.o: do_full_qdsum_wtrunc.c.o

.PHONY : do_full_qdsum_wtrunc.o

# target to build an object file
do_full_qdsum_wtrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum_wtrunc.c.o
.PHONY : do_full_qdsum_wtrunc.c.o

do_full_qdsum_wtrunc.i: do_full_qdsum_wtrunc.c.i

.PHONY : do_full_qdsum_wtrunc.i

# target to preprocess a source file
do_full_qdsum_wtrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum_wtrunc.c.i
.PHONY : do_full_qdsum_wtrunc.c.i

do_full_qdsum_wtrunc.s: do_full_qdsum_wtrunc.c.s

.PHONY : do_full_qdsum_wtrunc.s

# target to generate assembly for a file
do_full_qdsum_wtrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_full_qdsum_wtrunc.c.s
.PHONY : do_full_qdsum_wtrunc.c.s

do_kahan_sum.o: do_kahan_sum.c.o

.PHONY : do_kahan_sum.o

# target to build an object file
do_kahan_sum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum.c.o
.PHONY : do_kahan_sum.c.o

do_kahan_sum.i: do_kahan_sum.c.i

.PHONY : do_kahan_sum.i

# target to preprocess a source file
do_kahan_sum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum.c.i
.PHONY : do_kahan_sum.c.i

do_kahan_sum.s: do_kahan_sum.c.s

.PHONY : do_kahan_sum.s

# target to generate assembly for a file
do_kahan_sum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum.c.s
.PHONY : do_kahan_sum.c.s

do_kahan_sum_gcc_v.o: do_kahan_sum_gcc_v.c.o

.PHONY : do_kahan_sum_gcc_v.o

# target to build an object file
do_kahan_sum_gcc_v.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_gcc_v.c.o
.PHONY : do_kahan_sum_gcc_v.c.o

do_kahan_sum_gcc_v.i: do_kahan_sum_gcc_v.c.i

.PHONY : do_kahan_sum_gcc_v.i

# target to preprocess a source file
do_kahan_sum_gcc_v.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_gcc_v.c.i
.PHONY : do_kahan_sum_gcc_v.c.i

do_kahan_sum_gcc_v.s: do_kahan_sum_gcc_v.c.s

.PHONY : do_kahan_sum_gcc_v.s

# target to generate assembly for a file
do_kahan_sum_gcc_v.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_gcc_v.c.s
.PHONY : do_kahan_sum_gcc_v.c.s

do_kahan_sum_omp.o: do_kahan_sum_omp.c.o

.PHONY : do_kahan_sum_omp.o

# target to build an object file
do_kahan_sum_omp.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp.c.o
.PHONY : do_kahan_sum_omp.c.o

do_kahan_sum_omp.i: do_kahan_sum_omp.c.i

.PHONY : do_kahan_sum_omp.i

# target to preprocess a source file
do_kahan_sum_omp.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp.c.i
.PHONY : do_kahan_sum_omp.c.i

do_kahan_sum_omp.s: do_kahan_sum_omp.c.s

.PHONY : do_kahan_sum_omp.s

# target to generate assembly for a file
do_kahan_sum_omp.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp.c.s
.PHONY : do_kahan_sum_omp.c.s

do_kahan_sum_omp_wbittrunc.o: do_kahan_sum_omp_wbittrunc.c.o

.PHONY : do_kahan_sum_omp_wbittrunc.o

# target to build an object file
do_kahan_sum_omp_wbittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp_wbittrunc.c.o
.PHONY : do_kahan_sum_omp_wbittrunc.c.o

do_kahan_sum_omp_wbittrunc.i: do_kahan_sum_omp_wbittrunc.c.i

.PHONY : do_kahan_sum_omp_wbittrunc.i

# target to preprocess a source file
do_kahan_sum_omp_wbittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp_wbittrunc.c.i
.PHONY : do_kahan_sum_omp_wbittrunc.c.i

do_kahan_sum_omp_wbittrunc.s: do_kahan_sum_omp_wbittrunc.c.s

.PHONY : do_kahan_sum_omp_wbittrunc.s

# target to generate assembly for a file
do_kahan_sum_omp_wbittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_omp_wbittrunc.c.s
.PHONY : do_kahan_sum_omp_wbittrunc.c.s

do_kahan_sum_v.o: do_kahan_sum_v.c.o

.PHONY : do_kahan_sum_v.o

# target to build an object file
do_kahan_sum_v.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_v.c.o
.PHONY : do_kahan_sum_v.c.o

do_kahan_sum_v.i: do_kahan_sum_v.c.i

.PHONY : do_kahan_sum_v.i

# target to preprocess a source file
do_kahan_sum_v.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_v.c.i
.PHONY : do_kahan_sum_v.c.i

do_kahan_sum_v.s: do_kahan_sum_v.c.s

.PHONY : do_kahan_sum_v.s

# target to generate assembly for a file
do_kahan_sum_v.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_kahan_sum_v.c.s
.PHONY : do_kahan_sum_v.c.s

do_knuth_sum.o: do_knuth_sum.c.o

.PHONY : do_knuth_sum.o

# target to build an object file
do_knuth_sum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum.c.o
.PHONY : do_knuth_sum.c.o

do_knuth_sum.i: do_knuth_sum.c.i

.PHONY : do_knuth_sum.i

# target to preprocess a source file
do_knuth_sum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum.c.i
.PHONY : do_knuth_sum.c.i

do_knuth_sum.s: do_knuth_sum.c.s

.PHONY : do_knuth_sum.s

# target to generate assembly for a file
do_knuth_sum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum.c.s
.PHONY : do_knuth_sum.c.s

do_knuth_sum_v.o: do_knuth_sum_v.c.o

.PHONY : do_knuth_sum_v.o

# target to build an object file
do_knuth_sum_v.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum_v.c.o
.PHONY : do_knuth_sum_v.c.o

do_knuth_sum_v.i: do_knuth_sum_v.c.i

.PHONY : do_knuth_sum_v.i

# target to preprocess a source file
do_knuth_sum_v.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum_v.c.i
.PHONY : do_knuth_sum_v.c.i

do_knuth_sum_v.s: do_knuth_sum_v.c.s

.PHONY : do_knuth_sum_v.s

# target to generate assembly for a file
do_knuth_sum_v.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_knuth_sum_v.c.s
.PHONY : do_knuth_sum_v.c.s

do_ldsum.o: do_ldsum.c.o

.PHONY : do_ldsum.o

# target to build an object file
do_ldsum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum.c.o
.PHONY : do_ldsum.c.o

do_ldsum.i: do_ldsum.c.i

.PHONY : do_ldsum.i

# target to preprocess a source file
do_ldsum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum.c.i
.PHONY : do_ldsum.c.i

do_ldsum.s: do_ldsum.c.s

.PHONY : do_ldsum.s

# target to generate assembly for a file
do_ldsum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum.c.s
.PHONY : do_ldsum.c.s

do_ldsum_wbittrunc.o: do_ldsum_wbittrunc.c.o

.PHONY : do_ldsum_wbittrunc.o

# target to build an object file
do_ldsum_wbittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wbittrunc.c.o
.PHONY : do_ldsum_wbittrunc.c.o

do_ldsum_wbittrunc.i: do_ldsum_wbittrunc.c.i

.PHONY : do_ldsum_wbittrunc.i

# target to preprocess a source file
do_ldsum_wbittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wbittrunc.c.i
.PHONY : do_ldsum_wbittrunc.c.i

do_ldsum_wbittrunc.s: do_ldsum_wbittrunc.c.s

.PHONY : do_ldsum_wbittrunc.s

# target to generate assembly for a file
do_ldsum_wbittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wbittrunc.c.s
.PHONY : do_ldsum_wbittrunc.c.s

do_ldsum_wdigittrunc.o: do_ldsum_wdigittrunc.c.o

.PHONY : do_ldsum_wdigittrunc.o

# target to build an object file
do_ldsum_wdigittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wdigittrunc.c.o
.PHONY : do_ldsum_wdigittrunc.c.o

do_ldsum_wdigittrunc.i: do_ldsum_wdigittrunc.c.i

.PHONY : do_ldsum_wdigittrunc.i

# target to preprocess a source file
do_ldsum_wdigittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wdigittrunc.c.i
.PHONY : do_ldsum_wdigittrunc.c.i

do_ldsum_wdigittrunc.s: do_ldsum_wdigittrunc.c.s

.PHONY : do_ldsum_wdigittrunc.s

# target to generate assembly for a file
do_ldsum_wdigittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_ldsum_wdigittrunc.c.s
.PHONY : do_ldsum_wdigittrunc.c.s

do_pair_sum.o: do_pair_sum.c.o

.PHONY : do_pair_sum.o

# target to build an object file
do_pair_sum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_pair_sum.c.o
.PHONY : do_pair_sum.c.o

do_pair_sum.i: do_pair_sum.c.i

.PHONY : do_pair_sum.i

# target to preprocess a source file
do_pair_sum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_pair_sum.c.i
.PHONY : do_pair_sum.c.i

do_pair_sum.s: do_pair_sum.c.s

.PHONY : do_pair_sum.s

# target to generate assembly for a file
do_pair_sum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_pair_sum.c.s
.PHONY : do_pair_sum.c.s

do_qdsum.o: do_qdsum.c.o

.PHONY : do_qdsum.o

# target to build an object file
do_qdsum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum.c.o
.PHONY : do_qdsum.c.o

do_qdsum.i: do_qdsum.c.i

.PHONY : do_qdsum.i

# target to preprocess a source file
do_qdsum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum.c.i
.PHONY : do_qdsum.c.i

do_qdsum.s: do_qdsum.c.s

.PHONY : do_qdsum.s

# target to generate assembly for a file
do_qdsum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum.c.s
.PHONY : do_qdsum.c.s

do_qdsum_wtrunc.o: do_qdsum_wtrunc.c.o

.PHONY : do_qdsum_wtrunc.o

# target to build an object file
do_qdsum_wtrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum_wtrunc.c.o
.PHONY : do_qdsum_wtrunc.c.o

do_qdsum_wtrunc.i: do_qdsum_wtrunc.c.i

.PHONY : do_qdsum_wtrunc.i

# target to preprocess a source file
do_qdsum_wtrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum_wtrunc.c.i
.PHONY : do_qdsum_wtrunc.c.i

do_qdsum_wtrunc.s: do_qdsum_wtrunc.c.s

.PHONY : do_qdsum_wtrunc.s

# target to generate assembly for a file
do_qdsum_wtrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_qdsum_wtrunc.c.s
.PHONY : do_qdsum_wtrunc.c.s

do_sum.o: do_sum.c.o

.PHONY : do_sum.o

# target to build an object file
do_sum.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum.c.o
.PHONY : do_sum.c.o

do_sum.i: do_sum.c.i

.PHONY : do_sum.i

# target to preprocess a source file
do_sum.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum.c.i
.PHONY : do_sum.c.i

do_sum.s: do_sum.c.s

.PHONY : do_sum.s

# target to generate assembly for a file
do_sum.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum.c.s
.PHONY : do_sum.c.s

do_sum_omp.o: do_sum_omp.c.o

.PHONY : do_sum_omp.o

# target to build an object file
do_sum_omp.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp.c.o
.PHONY : do_sum_omp.c.o

do_sum_omp.i: do_sum_omp.c.i

.PHONY : do_sum_omp.i

# target to preprocess a source file
do_sum_omp.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp.c.i
.PHONY : do_sum_omp.c.i

do_sum_omp.s: do_sum_omp.c.s

.PHONY : do_sum_omp.s

# target to generate assembly for a file
do_sum_omp.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp.c.s
.PHONY : do_sum_omp.c.s

do_sum_omp_wbittrunc.o: do_sum_omp_wbittrunc.c.o

.PHONY : do_sum_omp_wbittrunc.o

# target to build an object file
do_sum_omp_wbittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp_wbittrunc.c.o
.PHONY : do_sum_omp_wbittrunc.c.o

do_sum_omp_wbittrunc.i: do_sum_omp_wbittrunc.c.i

.PHONY : do_sum_omp_wbittrunc.i

# target to preprocess a source file
do_sum_omp_wbittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp_wbittrunc.c.i
.PHONY : do_sum_omp_wbittrunc.c.i

do_sum_omp_wbittrunc.s: do_sum_omp_wbittrunc.c.s

.PHONY : do_sum_omp_wbittrunc.s

# target to generate assembly for a file
do_sum_omp_wbittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_omp_wbittrunc.c.s
.PHONY : do_sum_omp_wbittrunc.c.s

do_sum_wbittrunc.o: do_sum_wbittrunc.c.o

.PHONY : do_sum_wbittrunc.o

# target to build an object file
do_sum_wbittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wbittrunc.c.o
.PHONY : do_sum_wbittrunc.c.o

do_sum_wbittrunc.i: do_sum_wbittrunc.c.i

.PHONY : do_sum_wbittrunc.i

# target to preprocess a source file
do_sum_wbittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wbittrunc.c.i
.PHONY : do_sum_wbittrunc.c.i

do_sum_wbittrunc.s: do_sum_wbittrunc.c.s

.PHONY : do_sum_wbittrunc.s

# target to generate assembly for a file
do_sum_wbittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wbittrunc.c.s
.PHONY : do_sum_wbittrunc.c.s

do_sum_wdigittrunc.o: do_sum_wdigittrunc.c.o

.PHONY : do_sum_wdigittrunc.o

# target to build an object file
do_sum_wdigittrunc.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wdigittrunc.c.o
.PHONY : do_sum_wdigittrunc.c.o

do_sum_wdigittrunc.i: do_sum_wdigittrunc.c.i

.PHONY : do_sum_wdigittrunc.i

# target to preprocess a source file
do_sum_wdigittrunc.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wdigittrunc.c.i
.PHONY : do_sum_wdigittrunc.c.i

do_sum_wdigittrunc.s: do_sum_wdigittrunc.c.s

.PHONY : do_sum_wdigittrunc.s

# target to generate assembly for a file
do_sum_wdigittrunc.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/do_sum_wdigittrunc.c.s
.PHONY : do_sum_wdigittrunc.c.s

globalsums.o: globalsums.c.o

.PHONY : globalsums.o

# target to build an object file
globalsums.c.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/globalsums.c.o
.PHONY : globalsums.c.o

globalsums.i: globalsums.c.i

.PHONY : globalsums.i

# target to preprocess a source file
globalsums.c.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/globalsums.c.i
.PHONY : globalsums.c.i

globalsums.s: globalsums.c.s

.PHONY : globalsums.s

# target to generate assembly for a file
globalsums.c.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/globalsums.c.s
.PHONY : globalsums.c.s

kahan_agner_vector.o: kahan_agner_vector.cpp.o

.PHONY : kahan_agner_vector.o

# target to build an object file
kahan_agner_vector.cpp.o:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/kahan_agner_vector.cpp.o
.PHONY : kahan_agner_vector.cpp.o

kahan_agner_vector.i: kahan_agner_vector.cpp.i

.PHONY : kahan_agner_vector.i

# target to preprocess a source file
kahan_agner_vector.cpp.i:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/kahan_agner_vector.cpp.i
.PHONY : kahan_agner_vector.cpp.i

kahan_agner_vector.s: kahan_agner_vector.cpp.s

.PHONY : kahan_agner_vector.s

# target to generate assembly for a file
kahan_agner_vector.cpp.s:
	$(MAKE) -f CMakeFiles/globalsums.dir/build.make CMakeFiles/globalsums.dir/kahan_agner_vector.cpp.s
.PHONY : kahan_agner_vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... distclean"
	@echo "... globalsums"
	@echo "... do_full_qdsum.o"
	@echo "... do_full_qdsum.i"
	@echo "... do_full_qdsum.s"
	@echo "... do_full_qdsum_wtrunc.o"
	@echo "... do_full_qdsum_wtrunc.i"
	@echo "... do_full_qdsum_wtrunc.s"
	@echo "... do_kahan_sum.o"
	@echo "... do_kahan_sum.i"
	@echo "... do_kahan_sum.s"
	@echo "... do_kahan_sum_gcc_v.o"
	@echo "... do_kahan_sum_gcc_v.i"
	@echo "... do_kahan_sum_gcc_v.s"
	@echo "... do_kahan_sum_omp.o"
	@echo "... do_kahan_sum_omp.i"
	@echo "... do_kahan_sum_omp.s"
	@echo "... do_kahan_sum_omp_wbittrunc.o"
	@echo "... do_kahan_sum_omp_wbittrunc.i"
	@echo "... do_kahan_sum_omp_wbittrunc.s"
	@echo "... do_kahan_sum_v.o"
	@echo "... do_kahan_sum_v.i"
	@echo "... do_kahan_sum_v.s"
	@echo "... do_knuth_sum.o"
	@echo "... do_knuth_sum.i"
	@echo "... do_knuth_sum.s"
	@echo "... do_knuth_sum_v.o"
	@echo "... do_knuth_sum_v.i"
	@echo "... do_knuth_sum_v.s"
	@echo "... do_ldsum.o"
	@echo "... do_ldsum.i"
	@echo "... do_ldsum.s"
	@echo "... do_ldsum_wbittrunc.o"
	@echo "... do_ldsum_wbittrunc.i"
	@echo "... do_ldsum_wbittrunc.s"
	@echo "... do_ldsum_wdigittrunc.o"
	@echo "... do_ldsum_wdigittrunc.i"
	@echo "... do_ldsum_wdigittrunc.s"
	@echo "... do_pair_sum.o"
	@echo "... do_pair_sum.i"
	@echo "... do_pair_sum.s"
	@echo "... do_qdsum.o"
	@echo "... do_qdsum.i"
	@echo "... do_qdsum.s"
	@echo "... do_qdsum_wtrunc.o"
	@echo "... do_qdsum_wtrunc.i"
	@echo "... do_qdsum_wtrunc.s"
	@echo "... do_sum.o"
	@echo "... do_sum.i"
	@echo "... do_sum.s"
	@echo "... do_sum_omp.o"
	@echo "... do_sum_omp.i"
	@echo "... do_sum_omp.s"
	@echo "... do_sum_omp_wbittrunc.o"
	@echo "... do_sum_omp_wbittrunc.i"
	@echo "... do_sum_omp_wbittrunc.s"
	@echo "... do_sum_wbittrunc.o"
	@echo "... do_sum_wbittrunc.i"
	@echo "... do_sum_wbittrunc.s"
	@echo "... do_sum_wdigittrunc.o"
	@echo "... do_sum_wdigittrunc.i"
	@echo "... do_sum_wdigittrunc.s"
	@echo "... globalsums.o"
	@echo "... globalsums.i"
	@echo "... globalsums.s"
	@echo "... kahan_agner_vector.o"
	@echo "... kahan_agner_vector.i"
	@echo "... kahan_agner_vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

